#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/swarm-agent .
ID=$(docker create swarm)
docker cp ${ID}:/swarm .
docker rm -f ${ID}
docker build -t ${REPO}/swarm-agent:${TAG} .

echo Built ${REPO}/swarm-agent:${TAG}
